import { useState } from 'react'
import type { FormEvent } from 'react'
import { api } from '../api'

export default function LoginScreen({ onLogin }: { onLogin: (profile: unknown) => void }) {
  const [showPassword, setShowPassword] = useState(false), [registering, setRegistering] = useState(false), [accountName, setAccountName] = useState(''), [confirmPassword, setConfirmPassword] = useState(''), [authBusy, setAuthBusy] = useState(false), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [message, setMessage] = useState('')
  async function handleAuth(event: FormEvent) {
    event.preventDefault()
    if (registering && password !== confirmPassword) { setMessage('Passwords do not match.'); return }
    setAuthBusy(true); setMessage('')
    try { const data = await api(registering ? 'register' : 'login', 'POST', { email, password, ...(registering ? { name: accountName } : {}) }); onLogin(data.profile); setPassword(''); setConfirmPassword('') }
    catch (problem) { setMessage((problem as Error).message) } finally { setAuthBusy(false) }
  }
  return <main className="page-shell"><div className="orb orb-one" /><div className="orb orb-two" /><nav className="brand"><span className="brand-mark">गु</span><span>Guruji<span className="brand-ai">AI</span></span></nav><section className="hero-panel"><div className="eyebrow"><span>✦</span>Your personal AI teacher</div><h1>Har sawaal ka jawab.<br /><em>Har sapne ko udaan.</em></h1><p className="hero-copy">School se competitive exams tak personalised assessments, clear explanations aur focused practice.</p><div className="subject-row">{['K–12', 'NEET', 'JEE Advanced', 'SSC', 'Current Affairs'].map(item => <span key={item}>{item}</span>)}</div></section><aside className="login-card"><div className="login-top"><div className="mini-mark">गु</div><h2>{registering ? 'Create your account' : 'Welcome back!'}</h2><p>{registering ? 'Start your learning journey' : 'Continue your learning journey'}</p></div><form onSubmit={handleAuth}>{registering && <><label htmlFor="account-name">Your name</label><div className="input-wrap"><input id="account-name" value={accountName} onChange={event => setAccountName(event.target.value)} required /></div></>}<label htmlFor="email">Email address</label><div className="input-wrap"><span>✉</span><input id="email" type="email" value={email} onChange={event => setEmail(event.target.value)} required /></div><div className="label-row"><label htmlFor="password">{registering ? 'Password (minimum 8 characters)' : 'Password'}</label></div><div className="input-wrap"><span>◆</span><input id="password" type={showPassword ? 'text' : 'password'} minLength={registering ? 8 : 1} value={password} onChange={event => setPassword(event.target.value)} required /><button className="eye" type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? '◉' : '◎'}</button></div>{registering && <><label htmlFor="confirm-password">Confirm password</label><div className="input-wrap"><input id="confirm-password" type="password" minLength={8} value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} required /></div></>}<button className="login-button auth-submit" disabled={authBusy}>{authBusy ? 'Please wait…' : registering ? 'Create account' : 'Login to Guruji'} <span>→</span></button>{message && <p className="login-message error">{message}</p>}</form><p className="signup">{registering ? 'Already have an account? ' : 'New to Guruji? '}<button className="auth-switch" type="button" onClick={() => { setRegistering(!registering); setMessage('') }}>{registering ? 'Login' : 'Create an account'}</button></p></aside><footer>Built for curious minds <span>•</span> Learn without limits</footer></main>
}

